library(Quandl)
library(quantmod)
library(PerformanceAnalytics)
Sys.setenv(TZ = "UTC")
Quandl.api_key("LDvEJuPkQWrPGpHwokVx")
ImpCor <- Quandl("CBOE/SP500IMPCOR", type = 'xts', start_date = "2007-01-03")

IC08 <- na.omit(ImpCor[,3]) ; IC09 <- na.omit(ImpCor[,4])
IC10 <- na.omit(ImpCor[,5]) ; IC11 <- na.omit(ImpCor[,6])
IC12 <- na.omit(ImpCor[,7]) ; IC13 <- na.omit(ImpCor[,8])
IC14 <- na.omit(ImpCor[,9]) ; IC15 <- na.omit(ImpCor[,10])
IC16 <- na.omit(ImpCor[,11]); IC17 <- na.omit(ImpCor[,12])
IC18 <- na.omit(ImpCor[,13])
IC.cont <- rbind(IC08,IC09,IC10,IC11,IC12,IC13,IC14,IC15,IC16,IC17,IC18)
IC.wk <- to.period(IC.cont, period = 'weeks')

IC18.wk <- to.period(IC18, period = 'weeks')

getSymbols('^GSPC', src = 'yahoo', from = '2007-01-03')
SP.wk <- to.period(GSPC, periods = 'weeks')
SP.ret <- weeklyReturn(GSPC[,4], type = 'log')
SP.vol <- na.omit(volatility(SP.wk[,1:4], N = 260))
SP.lm <- cbind(SP.ret, "Days" = 1:length(SP.ret))

par(col = 'blue', mar = c(5,4,4,5))
plot(rollSFM(SP.lm[,1],SP.lm$Days)$beta, main = "SP500 Ret Slope vs SP500 Implied Correlation", xaxt = 'n', sub = 
       'High Implied Correlation = current trend can continue for 7-10 mos')
axis(side = 2)
mtext(side = 2, line = 2, 'S&P500 Returns Slope')
par(new = TRUE, col = "red", lty = 2)
plot(IC18.wk[,4], yaxt = "n", main = "")
axis(side = 4)
mtext(side = 4, line = 2, 'Implied Correlation(--)')

par(col = "black", lty = 1, mar = c(5,4,4,5))
plot(SP.vol[,1],  main = "SP500 Price Volatility vs SP500 Implied Correlation", xaxt = 'n')
#plot(SP.wk[,4],  main = "SP500 Price Volatility vs SP500 Implied Correlation", xaxt = 'n')
axis(side = 2)
mtext(side = 2, line = 2, 'S&P 500 Price Volatility')
par(new = TRUE, col = "red", lty = 2)
plot(IC.wk[,4], yaxt = "n", main = "")
#plot(lag(IC18W.inv,-6), yaxt = "n", main = "")
axis(side = 4)
mtext(side = 4, line = 2, 'Implied Correlation(--)')

layout(1:3)
par(col = 'black', lty = 1)
plot(SP.wk[,4]['2015:/'],  main = "SP500 Price")
plot(SP.vol[,1]['2015:/'],  main = "SP500 Price Volatility")
plot(IC.wk[,4]['2015:/'], main = "S&P500 Implied Correlation")

